---
- block:
  - name: "Run apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600
      force_apt_get: yes
    when: "{{ ENALBE_APT_UPDATE | default(false) }}"

- block:
  - name: "Update all packages to their latest version"
    apt:
      name: "*"
      state: latest
      force_apt_get: yes
    when: "{{ ENALBE_UPDATE_ALL_PKG | default(false) }}"

- block:
  - name: "Install packages"
    apt:
      name: "{{ item }}"
      state: present
      force_apt_get: yes
    with_items: "{{ PACKAGES_LIST }} "
    when: "{{ ENABLE_INSTALL_PKG | default(true) }}"
